ManagementSystem/ManagementSystem.Api/Controllers/SprintController.cs
using ManagementSystem.Api.Data;
using ManagementSystem.Api.Interfaces;
using ManagementSystem.Api.Models.ViewModels.Api;
using ManagementSystem.Api.Models.ViewModels.Sprint;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace ManagementSystem.Api.Controllers
{
    [Authorize]
    public class SprintController : Controller, ISprintController
    {
        private readonly ILogger<SprintController> _logger;
        private readonly ISprintRepository _sprintRepository;
        private readonly ISprintMapping _sprintMapping;
        private readonly ApplicationDbContext _dbContext;
        private readonly IModelStateService _modelStateService;

        public SprintController(ILogger<SprintController> logger, ISprintRepository sprintRepository, ISprintMapping sprintMapping, 
            ApplicationDbContext dbContext, IModelStateService modelStateService)
        {
            _logger = logger;
            _sprintRepository = sprintRepository;
            _sprintMapping = sprintMapping;
            _dbContext = dbContext;
            _modelStateService = modelStateService;
        }

        #region GET

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult SaveSprint(long? sprintId)
        {
            return ViewComponent("SprintSave", sprintId);
        }

        [HttpGet]
        public async Task<IActionResult> Details(long id)
        {
            var sprint = await _sprintRepository.GetByIdAsync(id);
            if (sprint == null)
            {
                //TODO: Error page for like this
            }



            return View();
        }

        #endregion

        #region POST

        [HttpPost]
        public async Task<IActionResult> SaveSprint(SaveSprintRequestViewModel request)
        {
            var result = new WebApiResult<SprintListViewModel>();

            result.Items = _modelStateService.ValidateRequest(ModelState);
            if (result.Items.Any())
            {
                return Json(new { result });
            }

            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier).Value;

            try
            {
                result.Success = await SaveItem(request, userId);
                result.Messages.Add(new ValidationItem()
                {
                    Message = "Very nice",
                    ValidationType = Models.Enums.ValidationTypes.Success
                });
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Exception occured while trying to save sprintId: " + request.Id + " for userId: " + userId);
                result.Messages.Add(new ValidationItem()
                {
                    Message = "Not so good",
                    ValidationType = Models.Enums.ValidationTypes.Error
                });
            }

            return Json(new { result });
        }

        #endregion

        private async Task<bool> SaveItem(SaveSprintRequestViewModel request, string userId)
        {
            Data.Entities.ApplicationSprint sprintToBeSaved = new Data.Entities.ApplicationSprint();
            if (request.Id.GetValueOrDefault() != 0)
            {
                sprintToBeSaved = await _sprintRepository.GetByIdAsync(request.Id.Value);
            }
            else
            {
                _dbContext.Add(sprintToBeSaved);
            }
            sprintToBeSaved = _sprintMapping.MapDatalayerFromViewModel(sprintToBeSaved, request);
            var result = _dbContext.SaveChanges();
            if (result == 1)
            {
                return true;
            }
            return false;
        }
    }
}

ManagementSystem/ManagementSystem.Api/Views/Shared/Components/SprintSave/_SprintSave.cshtml
@model ManagementSystem.Api.Models.ViewModels.Sprint.SaveSprintRequestViewModel

@{
}

<form asp-controller="Sprint" asp-action="SaveSprint" id="saveSprintForm">
    <div class="modal-header">
        <h5 class="modal-title">Save sprint</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="modal-body" id="saveSprintModalBody">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="row">
            @Html.HiddenFor(e => e.Id)
            <div class="col-6">
                <div class="form-group">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control" type="text" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Description" class="control-label"></label>
                    <input asp-for="Description" class="form-control" type="text" />
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
            </div>
            <div class="col-6">
                <div class="form-group date">
                    <label asp-for="StartDate">Start date</label>
                    <input type="text" asp-for="StartDate" />
                    <span asp-validation-for="StartDate" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="EndDate">End date</label>
                    <input type="text" asp-for="EndDate" />
                    <span asp-validation-for="EndDate" class="text-danger"></span>
                </div>
            </div>
        </div>
        <div class="modal-footer">
            <button type="submit" class="btn btn-primary relative" id="saveSprintBtn">Save</button>
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        </div>
    </div>
</form>